In [33]:
import re
import pandas as pd

In [46]:
# 로그의 각 행에 매치하는 정규 표현
pattern = re.compile('^\S+ \S+ \S+ \[(.*)\] "(.*)" (\S+) (\S+)$')

# 정규 표현으로 파싱하는 함수(일치하지 않는 행은 그냥 버린다)
def parse_access_log(path):
    for line in open(path, 'rb'):
        line = line.decode(encoding='ascii', errors='ignore')
        for m in pattern.finditer(line):
            yield m.groups()
            
# 로그 파일을 읽어서 데이터 프레임으로 변환
columns = ['time', 'request', 'status', 'bytes']

pd.DataFrame(parse_access_log('access_log_Jul95'), columns=columns)

,time,request,status,bytes
0,01/Jul/1995:00:00:01 -0400,GET /history/apollo/ HTTP/1.0,200,6245
1,01/Jul/1995:00:00:06 -0400,GET /shuttle/countdown/ HTTP/1.0,200,3985
2,01/Jul/1995:00:00:09 -0400,GET /shuttle/missions/sts-73/mission-sts-73.ht...,200,4085
3,01/Jul/1995:00:00:11 -0400,GET /shuttle/countdown/liftoff.html HTTP/1.0,304,0
4,01/Jul/1995:00:00:11 -0400,GET /shuttle/missions/sts-73/sts-73-patch-smal...,200,4179
5,01/Jul/1995:00:00:12 -0400,GET /images/NASA-logosmall.gif HTTP/1.0,304,0
6,01/Jul/1995:00:00:12 -0400,GET /shuttle/countdown/video/livevideo.gif HTT...,200,0
7,01/Jul/1995:00:00:12 -0400,GET /shuttle/countdown/countdown.html HTTP/1.0,200,3985
8,01/Jul/1995:00:00:13 -0400,GET /shuttle/countdown/ HTTP/1.0,200,3985
9,01/Jul/1995:00:00:13 -0400,GET / HTTP/1.0,200,7074
10,01/Jul/1995:00:00:14 -0400,GET /shuttle/countdown/count.gif HTTP/1.0,200,40310
11,01/Jul/1995:00:00:14 -0400,GET /images/NASA-logosmall.gif HTTP/1.0,200,786
12,01/Jul/1995:00:00:14 -0400,GET /images/KSC-logosmall.gif HTTP/1.0,200,1204
13,01/Jul/1995:00:00:15 -0400,GET /shuttle/countdown/count.gif HTTP/1.0,200,40310
14,01/Jul/1995:00:00:15 -0400,GET /images/NASA-logosmall.gif HTTP/1.0,200,786
15,01/Jul/1995:00:00:15 -0400,GET /images/KSC-logosmall.gif HTTP/1.0,200,1204
16,01/Jul/1995:00:00:17 -0400,GET /images/ksclogo-medium.gif HTTP/1.0,304,0
17,01/Jul/1995:00:00:17 -0400,GET /images/launch-logo.gif HTTP/1.0,200,1713
18,01/Jul/1995:00:00:18 -0400,GET /facts/about_ksc.html HTTP/1.0,200,3977
19,01/Jul/1995:00:00:19 -0400,GET /shuttle/missions/sts-71/images/KSC-95EC-0...,200,34029
20,01/Jul/1995:00:00:19 -0400,GET /images/launchpalms-small.gif HTTP/1.0,200,11473
21,01/Jul/1995:00:00:24 -0400,GET /shuttle/countdown/ HTTP/1.0,200,3985
22,01/Jul/1995:00:00:25 -0400,GET /shuttle/missions/51-l/mission-51-l.html H...,200,6723
23,01/Jul/1995:00:00:27 -0400,GET / HTTP/1.0,200,7074
24,01/Jul/1995:00:00:29 -0400,GET /shuttle/countdown/count.gif HTTP/1.0,200,40310
25,01/Jul/1995:00:00:33 -0400,GET /shuttle/missions/sts-71/sts-71-patch-smal...,200,12054
26,01/Jul/1995:00:00:35 -0400,GET /images/ksclogo-medium.gif HTTP/1.0,200,5866
27,01/Jul/1995:00:00:37 -0400,GET /shuttle/missions/sts-71/images/KSC-95EC-0...,200,61716
28,01/Jul/1995:00:00:38 -0400,GET /history/apollo/apollo-13/images/70HC314.G...,200,101267
29,01/Jul/1995:00:00:40 -0400,GET /images/NASA-logosmall.gif HTTP/1.0,200,786
...,...,...,...,...
1891683,28/Jul/1995:13:32:11 -0400,GET /elv/uplink2.htm HTTP/1.0,200,2031
1891684,28/Jul/1995:13:32:11 -0400,GET /shuttle/technology/images/srb_mod_compare...,200,36902
1891685,28/Jul/1995:13:32:12 -0400,GET /images/shuttle-patch-small.gif HTTP/1.0,200,4179
1891686,28/Jul/1995:13:32:12 -0400,GET /images/launch.gif HTTP/1.0,200,240458
1891687,28/Jul/1995:13:32:13 -0400,GET /history/apollo/images/footprint-small.gif...,200,18149
1891688,28/Jul/1995:13:32:14 -0400,GET /shuttle/countdown/liftoff.html HTTP/1.0,200,5220
1891689,28/Jul/1995:13:32:16 -0400,GET /images/MOSAIC-logosmall.gif HTTP/1.0,200,363
1891690,28/Jul/1995:13:32:16 -0400,GET /images/KSC-logosmall.gif HTTP/1.0,200,1204
1891691,28/Jul/1995:13:32:16 -0400,GET /images/launch-logo.gif HTTP/1.0,200,1713
1891692,28/Jul/1995:13:32:17 -0400,GET /shuttle/technology/sts-newsref/sts_egress...,200,86379
1891693,28/Jul/1995:13:32:18 -0400,GET /shuttle/technology/images/srb_mod_compare...,200,55666
1891694,28/Jul/1995:13:32:18 -0400,GET /shuttle/missions/sts-74/mission-sts-74.ht...,200,3790
1891695,28/Jul/1995:13:32:19 -0400,GET / HTTP/1.0,200,7280
1891696,28/Jul/1995:13:32:19 -0400,GET /facts/faq.html HTTP/1.0,200,18290
1891697,28/Jul/1995:13:32:20 -0400,GET /images/ksclogosmall.gif HTTP/1.0,200,3635
1891698,28/Jul/1995:13:32:20 -0400,GET /images/NASA-logosmall.gif HTTP/1.0,200,786
1891699,28/Jul/1995:13:32:20 -0400,GET /images/MOSAIC-logosmall.gif HTTP/1.0,200,363
1891700,28/Jul/1995:13:32:20 -0400,GET /images/USA-logosmall.gif HTTP/1.0,200,234
1891701,28/Jul/1995:13:32:21 -0400,GET /images/WORLD-logosmall.gif HTTP/1.0,200,669
1891702,28/Jul/1995:13:32:21 -0400,GET /images/faq.gif HTTP/1.0,200,263
1891703,28/Jul/1995:13:32:21 -0400,GET /images/ksclogosmall.gif HTTP/1.0,200,3635
1891704,28/Jul/1995:13:32:22 -0400,GET /images/USA-logosmall.gif HTTP/1.0,200,234
1891705,28/Jul/1995:13:32:22 -0400,GET /shuttle/technology/images/srb_mod_compare...,200,36902
1891706,28/Jul/1995:13:32:22 -0400,GET /images/shuttle-patch-logo.gif HTTP/1.0,200,891
1891707,28/Jul/1995:13:32:22 -0400,GET /shuttle/technology/images/srb_mod_compare...,200,55666
1891708,28/Jul/1995:13:32:22 -0400,GET /shuttle/technology/images/srb_mod_compare...,200,28219
1891709,28/Jul/1995:13:32:23 -0400,GET /images/KSC-logosmall.gif HTTP/1.0,200,1204
1891710,28/Jul/1995:13:32:23 -0400,GET /shuttle/missions/missions.html HTTP/1.0,200,8677
1891711,28/Jul/1995:13:32:23 -0400,GET /images/ksclogo-medium.gif HTTP/1.0,200,5866
1891712,28/Jul/1995:13:32:25 -0400,GET /shuttle/missions/sts-74/sts-74-patch-smal...,200,5494

In [52]:
# 데이터 프레임을 변수에 보관하기
df = pd.DataFrame(parse_access_log('access_log_Jul95'), columns=columns)

In [53]:
# 'time' 칼럼을 덮어쓴다(타임 존 버리기)
df.time = pd.to_datetime(df.time, format='%d/%b/%Y:%X', exact=False)

In [49]:
df.head()

,time,request,status,bytes
0,1995-07-01 00:00:01,GET /history/apollo/ HTTP/1.0,200,6245
1,1995-07-01 00:00:06,GET /shuttle/countdown/ HTTP/1.0,200,3985
2,1995-07-01 00:00:09,GET /shuttle/missions/sts-73/mission-sts-73.ht...,200,4085
3,1995-07-01 00:00:11,GET /shuttle/countdown/liftoff.html HTTP/1.0,304,0
4,1995-07-01 00:00:11,GET /shuttle/missions/sts-73/sts-73-patch-smal...,200,4179

In [54]:
# csv 파일로 보관
df.to_csv('access_log.csv', index=False)